apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .argo/linkerd/*
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/cbrandborg/dummy-argocd
    targetRevision: main
    path: ./argo/argo-config
  syncPolicy: 
    automated:
      prune: true