apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .argo/cert-manager/*
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/cbrandborg/dummy-argocd'
    targetRevision: main
    path: .argo/cert-manager/*
    helm:
      releaseName: cert-manager        
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true