# Deploying applicationSet for cert-manager to be deployed in all clusters (mgmt, staging, prod)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .argo/cert-manager/*
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: 'https://github.com/cbrandborg/dummy-argocd'
    targetRevision: main
    path: .argo/cert-manager/*
    helm:
      releaseName: cert-manager        

  destination:
    server: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true