apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .argo/external-dns/*
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/cbrandborg/dummy-argocd
    targetRevision: main
    path: ./argo/external-dns
  syncPolicy: 
    automated:
      prune: true