apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-req-crds-linkerd-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ./argo/pre-req-crds-linkerd
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/cbrandborg/dummy-argocd
    targetRevision: main
    path: ./argo/pre-req-crds-linkerd/*
  syncPolicy:
    automated: {}