
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .argo/linkerd/*
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    name: in-cluster 
    namespace: default 
  project: default 
  source:
    repoURL: https://github.com/cbrandborg/dummy-argocd
    targetRevision: main 
    path: ./argo/linkerd
    helm:
      releaseName: linkerd
  syncPolicy:
    automated:
      prune: true 