linkerd-control-plane:
  identity:
    # -- If the linkerd-identity-trust-roots ConfigMap has already been created
    externalCA: true

    # -- Use [Service Account token Volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) for pod validation instead of the default token
    serviceAccountTokenProjection: true
    issuer:
      scheme: kubernetes.io/tls

      # -- Amount of time to allow for clock skew within a Linkerd cluster
      clockSkewAllowance: 20s

      # -- Amount of time for which the Identity issuer should certify identity
      issuanceLifetime: 24h0m0s
