apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    email: techops@cellpointmobile.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-mgmt
    solvers:
    - selector: {}
      dns01:
        cloudDNS:
          project: prj-cp-mgmt-compute
---
# https://trstringer.com/admission-control-cert-manager/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-self-signed
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-root
spec:
  ca:
    secretName: ca-root
